# Example markdownlint YAML configuration with all properties set to their default value

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null


# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 80
  # Number of characters for headings
  heading_line_length: 140
  # Number of characters for code blocks
  code_block_line_length: 80
  # Include code blocks
  code_blocks: false
  # Include tables
  tables: false
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
  
# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  # Punctuation characters
  punctuation: ".,;:!。，；：！"

MD033: false
no-inline-html:
  allowed_elements: [ "details", "h1", "p", "small", "br"]